[package]
name = "camctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arducam_mipicamera = { git="https://github.com/sjbeskur/arducam-mipicamera-rs.git", branch="main"}
image = "0.24.6"
